### PR TITLE
Add Italian translations

### PR DESCRIPTION
**Pull request by alessandroias**
Buongiorno Spook 👻

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Grazie! 🇮🇹 

../Frenck

**Comment by alessandroias** [comment]
I'm looking for a word pun that works in Italian, but it's not as simple as it seems. As soon as I find it, I'll do a new PR.

**Comment by alessandroias** [comment]
How about "pessimo coinquilino"? Which in Italian stands for "really bad home mate"?

**Comment by alessandroias** [comment]
> How about "pessimo coinquilino"? Which in Italian stands for "really bad home mate"?

@frenck would you prefer to keep the sentence in english as now or update with the suggestion above?

**Comment by frenck** [comment]
👻 doesn't care... 😁 

So, feel free to do what you think is right.

**Pull request merged**
